version: '3.8'

networks:
  eureka-network:


services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cloud_project_db
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "root",
          "-d",
          "cloud_project_db"
        ]
      interval: 10s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    image: theocohen25/cloud-project:cloud-frontend
    ports:
      - "5173:5173"
    networks:
      eureka-network:


  registry:
    image: theocohen25/cloud-project:registry-server
    ports:
      - "8761:8761"
    depends_on:
      db:
        condition: service_healthy
    networks:
      eureka-network:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway:
    image: theocohen25/cloud-project:api-gateway
    ports:
      - "9000:9000"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      eureka-network:
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/

  todo-services:
    image: theocohen25/cloud-project:todo-services
    ports:
      - "8082:8082"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      eureka-network:
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/

  user-services:
    image: theocohen25/cloud-project:user-services
    ports:
      - "8081:8081"
    depends_on:
      registry:
        condition: service_healthy
    networks:
      eureka-network:
    environment:
      - eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
